backend:
  name: github
  repo: alkyoness/datam
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "guides"
    label: "Klinik Rehberler"
    folder: "content/guides"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Tarih", name: "date", widget: "datetime"}
      - {label: "İçerik", name: "body", widget: "markdown"}
